// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/layout/navigation";
import { Metadata } from "next";
import Footer from "./components/common/button/footer/Footer";

// const geistSans = Geist({
//   subsets: ["latin"],
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className=''>

        <Navigation />

        <main>{children}</main>
        <Footer />
        <footer className="bg-secondary text-white p-4 text-center">
          <p>&copy; {new Date().getFullYear()} Lost Key. All rights reserved.</p>
        </footer>

      </body>
    </html>
  );
}
